plugin: # основные настройки плагина
  language: ru # язык сообщений (папка messages)
  debug: false

economy:
  symbols:
    vault: '⛏'

clan:
  create-cost: 10000
  name-length: 3..3
  name-symbols: 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
  levels:
    cost: 10000..50000
    resources:
      - 'COBBLESTONE 64 0.5'
      - 'STONE 256 0.5'
  storage:
    start-slots: 9
    cost: 25000..50000
    slots-per-upgrade: 9