name: GoldClans
version: '1.0'
main: me.korolkotov.goldclans.Main
api-version: '1.21'
author: KoroLKotov

softdepend: [Vault, PlaceholderAPI, MythicMobs]

commands:
  goldclan:
    aliases: [clan, gc]
    description: 'Основная команда плагина GoldClans.'
  clanchat:
    aliases: [cc]
    description: 'Команда кланового чата плагина GoldClans.'